### ISSUE TITLE
Allow minimum inject power above 200W

### ISSUE THREAD

**Issue by eliasvoe** [eet-energy/solmate-sdk#11]
In order to control the Solmate via an external home automation system such as Home Assistant together with a home energy meter, it is very important to set a higher minimum injection power than the current 200W. I would like to be able to set a value up to the maximum power of 800W to discharge the battery on sunny days.

**Comment by mmattel** [comment]
See my repo: https://github.com/mmattel/EET-Solmate/releases/tag/v5.0.0
You can now write back values from HA via MQTT to the Solmate.

**Comment by felixmark** [comment]
It is now possible to set a minimum injection of up to 800 W by using the set_user_minimum_injection route.
